services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio-server
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"  # API Port
      - "9001:9001"  # Console Port
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - ${MINIO_VOL_PATH}:/data
    restart: always
    networks:
      - minio_net

networks:
  minio_net:
    driver: bridge
